nerdfont: true
merge_strategy: rebase
window_prefix: wm-
mode: session
auto_name:
  command: command opencode run

windows:
  - name: work
    panes:
      - {}
      - command: command opencode
        split: horizontal
        target: 0
        percentage: 50
        focus: true
